DEFAULT_SEGMENTATION_ALG = 'FFA'
DEFAULT_SEGMENTATION_ENTROPY = 1
DEFAULT_SEGMENTATION_DIMENSION = 2
DEFAULT_SEGMENTATION_GAMA = 1

DEFAULT_SEGMENTATION_ENTROPY_LABEL = "Entropia (q)"
DEFAULT_SEGMENTATION_DIMENSION_LABEL = "Dimensão"
DEFAULT_SEGMENTATION_GAMA_LABEL = "Gama"
